services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: nulisaseqr-test
    command: Rscript --vanilla -e "testthat::test_dir('/workingDir/tests/testthat/')"
