FROM nulisaseq_r:latest

EXPOSE 8000

WORKDIR /workingDir
COPY ./tests/ /workingDir/tests/
COPY ./inst /workingDir/inst/

RUN set -eu; \
  install.r withr \
    > /tmp/install.log 2>&1; \
    cat /tmp/install.log; \
    if grep -qi "not available for this version of R" /tmp/install.log; then \
        package=$(grep -Eo '‘[[:alnum:]]+’' /tmp/install.log | tr -d '‘’'); \
        echo "Problem with installing R packages: ${package}"; \
        exit 1; \
    fi; \
    rm -rf /tmp/install.log;
CMD ["bash"]
